version: '3.1'

services:
  app:
    build: ./app
    depends_on:
      - "db"
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - vars.env
  stream_retriever:
    build: ./stream_retriever
    depends_on:
      - "db"
    restart: always
    env_file:
      - vars.env
  db:
    image: postgres:9.6.6
    restart: always
    ports:
      - "5432:5432"
    env_file: 
      - vars.env
    volumes:
      - /var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql